# Generated by Django 4.1.7 on 2023-03-05 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=100)),
                ("Phone", models.IntegerField(default=0)),
                ("Email", models.CharField(max_length=100)),
                ("Pan_Number", models.IntegerField(default=" ")),
                ("Pin_Code", models.IntegerField(default=" ")),
                ("Looking_for", models.CharField(max_length=100)),
                ("Requirnment", models.TextField()),
            ],
        ),
    ]
