# Generated by Django 4.1.7 on 2023-03-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Jobs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Job_Title", models.CharField(max_length=100)),
                ("Education_Requriement", models.CharField(max_length=200)),
                ("Experience_Requriement", models.IntegerField(default=" ")),
                ("Job_Location", models.CharField(max_length=100)),
                ("More_Details", models.TextField()),
            ],
        ),
    ]
