# Generated by Django 4.1.7 on 2023-03-05 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0002_jobs"),
    ]

    operations = [
        migrations.RemoveField(model_name="jobs", name="More_Details",),
        migrations.AddField(
            model_name="jobs", name="Details", field=models.TextField(default=" "),
        ),
        migrations.AddField(
            model_name="jobs",
            name="Job_summary",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="jobs",
            name="Principal_Responsibilities",
            field=models.TextField(default=" "),
        ),
        migrations.AlterField(
            model_name="jobs",
            name="Experience_Requriement",
            field=models.IntegerField(default=0),
        ),
    ]
