# Generated by Django 4.1.7 on 2023-03-05 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0003_remove_jobs_more_details_jobs_details_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job_Form",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=100)),
                ("Phone", models.IntegerField(default=0)),
                ("Email", models.CharField(max_length=100)),
                ("Position_apply", models.CharField(max_length=100)),
                ("Resume", models.FileField(upload_to="")),
            ],
        ),
    ]
