# Generated by Django 4.1.3 on 2023-03-06 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0004_job_form"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reviews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Tell", models.TextField()),
                ("Name", models.CharField(max_length=100)),
                ("Profession", models.CharField(max_length=100)),
                ("Age", models.IntegerField(default=0)),
                ("Place", models.CharField(max_length=100)),
            ],
        ),
    ]
