# Generated by Django 4.1.3 on 2023-03-06 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0005_reviews"),
    ]

    operations = [
        migrations.CreateModel(
            name="Credit_Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=100)),
                ("Phone", models.IntegerField(default=0)),
                ("Email", models.CharField(max_length=100)),
                ("Pan_No", models.IntegerField(default=0)),
                ("Apply_for", models.CharField(max_length=200)),
            ],
        ),
    ]
